<a href="https://colab.research.google.com/github/hyel0000/2023-weather-big-data-contest/blob/main/model_lightgbm_(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install -U imbalanced-learn
!pip install optuna

Requirement already satisfied: imbalanced-learn in /usr/local/lib/python3.10/dist-packages (0.10.1)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.10/dist-packages (from imbalanced-learn) (1.22.4)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.10/dist-packages (from imbalanced-learn) (1.10.1)
Requirement already satisfied: scikit-learn>=1.0.2 in /usr/local/lib/python3.10/dist-packages (from imbalanced-learn) (1.2.2)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from imbalanced-learn) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from imbalanced-learn) (3.1.0)
Collecting optuna
  Downloading optuna-3.2.0-py3-none-any.whl (390 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 390.6/390.6 kB 7.5 MB/s eta 0:00:00
Collecting alembic>=1.5.0 (from optuna)
  Downloading alembic-1.11.1-py3-none-any.whl (224 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 224.5/224.5 kB 24.4 MB/s eta 0:00:00
Collecting cmaes>=0.9.1 (from optuna)
  Downloading cmaes-0.9.1-py3-none-any.whl (21 kB)
Collecting colorlog (from optuna)
  Downloading colorlog-6.7.0-py2.py3-none-any.whl (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from optuna) (1.22.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from optuna) (23.1)
Requirement already satisfied: sqlalchemy>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from optuna) (2.0.16)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from optuna) (4.65.0)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.10/dist-packages (from optuna) (6.0)
Collecting Mako (from alembic>=1.5.0->optuna)
  Downloading Mako-1.2.4-py3-none-any.whl (78 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.7/78.7 kB 10.8 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions>=4 in /usr/local/lib/python3.10/dist-packages (from alembic>=1.5.0->optuna) (4.6.3)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy>=1.3.0->optuna) (2.0.2)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.10/dist-packages (from Mako->alembic>=1.5.0->optuna) (2.1.3)
Installing collected packages: Mako, colorlog, cmaes, alembic, optuna
Successfully installed Mako-1.2.4 alembic-1.11.1 cmaes-0.9.1 colorlog-6.7.0 optuna-3.2.0

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive/')

Mounted at /content/gdrive/

In [ ]:
# random_seed fix
import numpy as np
import random
seed = 1375
random.seed(seed)
np.random.seed(seed)

#울산

In [ ]:
import pandas as pd
ulsan = pd.read_csv('/content/gdrive/MyDrive/2023날씨빅콘/final_data/final_csv/가까운거리/울산_가까운거리_train_최종.csv',index_col=0)
ulsan

,ulsan_drag_train_final.num,ulsan_drag_train_final.time,ulsan_drag_train_final.latitude,ulsan_drag_train_final.longitude,ulsan_drag_train_final.sog,ulsan_drag_train_final.cog,ulsan_drag_train_final.hdg,stn_num,target,kma_pagobuoy_train.stn_name,...,kma_pagobuoy_train.max_wh,kma_pagobuoy_train.sig_wh,kma_pagobuoy_train.mean_wh,kma_lightbecon_train.stn,kma_lightbecon_train.stn_name,kma_lightbecon_train.wd,kma_lightbecon_train.ws,khnp_buoy_train.stn_name,khnp_buoy_train.ws,khnp_buoy_train.wd
0,1,2021-02-14 14:37:11,"""N35.433233""","""E129.458967""",0.2,60.0,204.0,E2,0,간절곶,...,0.8,0.6,0.4,963.0,Idukseo,172.0,2.0,Gori,14.8,122.0
1,1,2021-02-14 14:37:21,"""N35.433233""","""E129.458983""",0.2,53.0,204.0,E2,0,간절곶,...,0.8,0.6,0.4,963.0,Idukseo,172.0,2.0,Gori,14.8,122.0
2,1,2021-02-14 14:37:33,"""N35.433250""","""E129.459000""",0.2,45.0,203.0,E2,0,간절곶,...,0.8,0.6,0.4,963.0,Idukseo,172.0,2.0,Gori,14.8,122.0
3,1,2021-02-14 14:37:42,"""N35.433250""","""E129.459000""",0.2,44.0,203.0,E2,0,간절곶,...,0.8,0.6,0.4,963.0,Idukseo,172.0,2.0,Gori,14.8,122.0
4,1,2021-02-14 14:37:52,"""N35.433267""","""E129.459017""",0.2,41.0,203.0,E2,0,간절곶,...,0.8,0.6,0.4,963.0,Idukseo,172.0,2.0,Gori,14.8,122.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
388238,1127,2022-02-06 23:00:59,"""N35.459582""","""E129.416498""",0.1,246.5,315.0,E1,0,간절곶,...,0.6,0.5,0.3,963.0,Idukseo,297.0,3.8,Gori,21.6,211.0
388239,1127,2022-02-06 23:04:03,"""N35.459568""","""E129.416445""",0.0,301.3,322.0,E1,0,간절곶,...,0.6,0.5,0.3,963.0,Idukseo,303.0,3.8,Gori,20.6,210.0
388240,1127,2022-02-06 23:07:00,"""N35.459557""","""E129.416562""",0.3,98.9,317.0,E1,0,간절곶,...,0.6,0.5,0.3,963.0,Idukseo,306.0,5.4,Gori,19.5,228.0
388241,1127,2022-02-06 23:10:02,"""N35.459630""","""E129.416552""",0.2,322.3,305.0,E1,0,간절곶,...,0.6,0.5,0.3,963.0,Idukseo,310.0,6.5,Gori,20.8,211.0
388242,1127,2022-02-06 23:13:00,"""N35.459640""","""E129.416417""",0.2,244.3,306.0,E1,0,간절곶,...,0.6,0.5,0.3,963.0,Idukseo,310.0,7.3,Gori,30.8,215.0

In [ ]:
ulsan_test = pd.read_csv('/content/gdrive/MyDrive/2023날씨빅콘/final_data/final_csv/가까운거리/울산_가까운거리_test_최종.csv',index_col=0)
ulsan_test

,ulsan_anch_drag_test.area,ulsan_anch_drag_test.time,ulsan_anch_drag_test.num,ulsan_anch_drag_test.lat,ulsan_anch_drag_test.lon,ulsan_anch_drag_test.sog,ulsan_anch_drag_test.cog,ulsan_anch_drag_test.hdg,stn_num,kma_pagobuoy_test.stn_name,...,kma_pagobuoy_test.max_wh,kma_pagobuoy_test.sig_wh,kma_pagobuoy_test.mean_wh,kma_lightbecon_test.stn,kma_lightbecon_test.stn_name,kma_lightbecon_test.wd,kma_lightbecon_test.ws,khnp_buoy_test.stn_name,khnp_buoy_test.ws,khnp_buoy_test.wd
0,"""ULSAN""",2022-08-24 14:41:34,1001,"""N35.442767""","""E129.415550""",0.6,231.0,116.0,E1,간절곶,...,2.0,1.5,0.9,963.0,Idukseo,31.0,9.0,Gori,52.204831,156.321929
1,"""ULSAN""",2022-08-24 14:41:44,1001,"""N35.442767""","""E129.415500""",0.8,240.0,115.0,E1,간절곶,...,2.0,1.5,0.9,963.0,Idukseo,31.0,9.0,Gori,52.204831,156.321929
2,"""ULSAN""",2022-08-24 14:41:53,1001,"""N35.442750""","""E129.415467""",0.7,258.0,116.0,E1,간절곶,...,2.0,1.5,0.9,963.0,Idukseo,31.0,9.0,Gori,52.204831,156.321929
3,"""ULSAN""",2022-08-24 14:42:04,1001,"""N35.442750""","""E129.415417""",0.8,254.0,116.0,E1,간절곶,...,2.0,1.5,0.9,963.0,Idukseo,33.0,8.9,Gori,52.205609,156.320409
4,"""ULSAN""",2022-08-24 14:42:14,1001,"""N35.442733""","""E129.415367""",1.0,253.0,117.0,E1,간절곶,...,2.0,1.5,0.9,963.0,Idukseo,33.0,8.9,Gori,52.205609,156.320409
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186508,"""ULSAN""",2023-01-17 19:44:27,1117,"""N35.456302""","""E129.424155""",0.1,325.8,312.0,E1,간절곶,...,0.8,0.6,0.4,963.0,Idukseo,334.0,11.4,Gori,8.000000,21.000000
186509,"""ULSAN""",2023-01-17 19:50:27,1117,"""N35.456108""","""E129.424060""",0.3,71.3,338.0,E1,간절곶,...,0.8,0.6,0.4,963.0,Idukseo,338.0,11.8,Gori,16.400000,38.000000
186510,"""ULSAN""",2023-01-17 19:56:27,1117,"""N35.456153""","""E129.424177""",0.1,195.9,325.0,E1,간절곶,...,0.8,0.6,0.4,963.0,Idukseo,334.0,12.5,Gori,10.900000,52.000000
186511,"""ULSAN""",2023-01-17 19:59:24,1117,"""N35.456200""","""E129.424007""",0.1,274.4,324.0,E1,간절곶,...,0.8,0.6,0.4,963.0,Idukseo,335.0,11.4,Gori,16.200000,23.000000
186512,"""ULSAN""",2023-01-17 20:05:24,1117,"""N35.456177""","""E129.424080""",0.3,150.6,326.0,E1,간절곶,...,0.7,0.5,0.3,963.0,Idukseo,336.0,11.5,Gori,16.900000,47.000000

In [ ]:
import matplotlib.pyplot as plt

## 전처리

In [ ]:
ulsan = ulsan.drop(columns=['ulsan_drag_train_final.num','ulsan_drag_train_final.time','ulsan_drag_train_final.latitude', 'ulsan_drag_train_final.longitude',
                    'kma_pagobuoy_train.stn_name', 'kma_pagobuoy_train.stn','kma_lightbecon_train.stn',
                    'kma_lightbecon_train.stn_name','khnp_buoy_train.stn_name','kma_pagobuoy_train.mean_wh','kma_pagobuoy_train.max_wh'])

In [ ]:
ulsan_test = ulsan_test.drop(columns=['ulsan_anch_drag_test.area', 'ulsan_anch_drag_test.time','ulsan_anch_drag_test.num', 'ulsan_anch_drag_test.lat','ulsan_anch_drag_test.lon',
                                      'kma_pagobuoy_test.stn_name', 'kma_pagobuoy_test.stn','kma_lightbecon_test.stn','kma_lightbecon_test.stn_name','khnp_buoy_test.stn_name',
                                      'kma_pagobuoy_test.mean_wh','kma_pagobuoy_test.max_wh'])

In [ ]:
ulsan.columns = ['ulsan_anch_drag_test.sog', 'ulsan_anch_drag_test.cog',
       'ulsan_anch_drag_test.hdg', 'stn_num', 'target',
       'kma_pagobuoy_test.sig_wh',
       'kma_lightbecon_test.wd', 'kma_lightbecon_test.ws', 'khnp_buoy_test.ws',
       'khnp_buoy_test.wd']

In [ ]:
feature=['ulsan_anch_drag_test.sog', 'ulsan_anch_drag_test.cog',
       'ulsan_anch_drag_test.hdg', 'stn_num',
       'kma_pagobuoy_test.sig_wh',
       'kma_lightbecon_test.wd', 'kma_lightbecon_test.ws', 'khnp_buoy_test.ws',
       'khnp_buoy_test.wd']

y_feature=['target']

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le=le.fit(ulsan['stn_num'])
ulsan['stn_num']=le.transform(ulsan['stn_num'])
ulsan_test['stn_num'] = le.transform(ulsan_test['stn_num'])

##모델링

In [ ]:
from lightgbm.sklearn import LGBMClassifier
from imblearn.over_sampling import SMOTENC
from imblearn.over_sampling import SMOTE
import optuna
from lightgbm import LGBMRegressor, Dataset
from optuna.samplers import TPESampler
from sklearn.model_selection import StratifiedKFold, KFold
from optuna.samplers import TPESampler
from sklearn.metrics import f1_score
from tqdm import tqdm
import warnings
warnings.filterwarnings('ignore')


test_x = ulsan_test[feature]

ulsan_preds = []
kf = StratifiedKFold(n_splits=5, shuffle=True, random_state=seed)

for f, (train_idx, val_idx) in enumerate(tqdm(kf.split(range(len(ulsan)), y=ulsan['target']))):
    train_x = ulsan[feature].iloc[train_idx]
    valid_x = ulsan[feature].iloc[val_idx]
    y_train = ulsan[y_feature].iloc[train_idx]
    y_valid = ulsan[y_feature].iloc[val_idx]


    #sm = SMOTENC(categorical_features=[3], random_state=seed)
    #train_x, y_train = sm.fit_resample(train_x, y_train)

    sm = SMOTE(sampling_strategy=1)
    train_x, y_train = sm.fit_resample(train_x, y_train)



    preds = []
    train_y = y_train[y_feature]
    valid_y = y_valid[y_feature]

    sampler = TPESampler(seed=seed)

    def objective(trial):

            param = {
                'random_state' : seed,
                'metric'    : 'logloss',
                #'max_depth' : trial.suggest_int('max_depth', 10, 25),
                'max_depth' : -1,
                'learning_rate': trial.suggest_float('learning_rate', 1e-3, 0.1),
                'n_estimators': trial.suggest_int('n_estimators', 100, 2000),
                #'num_leaves'  : trial.suggest_int('num_leaves', 31, 1024),
                'num_leaves' : 31,
                'colsample_bytree' : trial.suggest_float('colsample_bytree', 0.5, 1.0),
                'subsample' :trial.suggest_float('subsample', 0.5, 1.0),
                'reg_alpha' : trial.suggest_float('reg_alpha', 0.0, 5.0),
                'reg_lambda' : trial.suggest_float('reg_lambda', 0.0, 5.0),
                'n_jobs' : -1,
                'boost_from_average' : False
            }

            model = LGBMClassifier(**param)
            model.fit(train_x, y_train, eval_set=[(valid_x, y_valid)], eval_metric = 'logloss', verbose=0)

            y_valid_pred = model.predict(valid_x)
            return f1_score(y_valid, y_valid_pred)

    study = optuna.create_study(direction='maximize', sampler=sampler)
    study.optimize(objective, n_trials=10)

    print('Best trial : score {}, \nparams {}'.format(study.best_trial.value, study.best_trial.params))

    model = LGBMClassifier(**study.best_params, random_state=seed, metric='logloss', n_jobs=-1)
    model.fit(train_x, train_y, eval_set=[(valid_x, valid_y)], eval_metric = 'logloss', verbose=0)

    # 확률값 출력
    #pred = model.predict(test_x)
    pred = model.predict_proba(test_x)[:,1]

    preds.append(pred)
    ulsan_preds.append(preds)

0it [00:00, ?it/s][I 2023-07-06 05:20:42,719] A new study created in memory with name: no-name-8f6d2ba6-47e0-482e-a7ae-afa86cdf6ba5
[I 2023-07-06 05:21:47,732] Trial 0 finished with value: 0.8042635658914727 and parameters: {'learning_rate': 0.05155075222533945, 'n_estimators': 1021, 'colsample_bytree': 0.719350443033115, 'subsample': 0.8026671775328005, 'reg_alpha': 2.929838278776278, 'reg_lambda': 4.381363801434478}. Best is trial 0 with value: 0.8042635658914727.
[I 2023-07-06 05:22:23,921] Trial 1 finished with value: 0.6682316118935838 and parameters: {'learning_rate': 0.03335122173910602, 'n_estimators': 449, 'colsample_bytree': 0.8939597454392421, 'subsample': 0.90185383175199, 'reg_alpha': 0.8325287193873104, 'reg_lambda': 4.1249853208318505}. Best is trial 0 with value: 0.8042635658914727.
[I 2023-07-06 05:22:52,557] Trial 2 finished with value: 0.7140849030081529 and parameters: {'learning_rate': 0.04819051340299198, 'n_estimators': 426, 'colsample_bytree': 0.8867573880389659, 'subsample': 0.7986835712080858, 'reg_alpha': 1.4341480205048074, 'reg_lambda': 4.11778941543427}. Best is trial 0 with value: 0.8042635658914727.
[I 2023-07-06 05:24:19,127] Trial 3 finished with value: 0.8294807370184255 and parameters: {'learning_rate': 0.049031124189119285, 'n_estimators': 1789, 'colsample_bytree': 0.5354452465687923, 'subsample': 0.6551634914707407, 'reg_alpha': 4.443349592067058, 'reg_lambda': 3.275406024914261}. Best is trial 3 with value: 0.8294807370184255.
[I 2023-07-06 05:25:27,991] Trial 4 finished with value: 0.8310901749663526 and parameters: {'learning_rate': 0.06022017902190689, 'n_estimators': 1492, 'colsample_bytree': 0.6792704767870048, 'subsample': 0.5551904219339706, 'reg_alpha': 4.8168769859021126, 'reg_lambda': 2.278705614545406}. Best is trial 4 with value: 0.8310901749663526.
[I 2023-07-06 05:25:52,359] Trial 5 finished with value: 0.788413098236776 and parameters: {'learning_rate': 0.08609403225492421, 'n_estimators': 482, 'colsample_bytree': 0.6371508281671892, 'subsample': 0.7335093601899446, 'reg_alpha': 2.774451765836108, 'reg_lambda': 2.5463458419800755}. Best is trial 4 with value: 0.8310901749663526.
[I 2023-07-06 05:26:33,742] Trial 6 finished with value: 0.4832491109863373 and parameters: {'learning_rate': 0.0052700473338712, 'n_estimators': 748, 'colsample_bytree': 0.9391703358009253, 'subsample': 0.9307535035437619, 'reg_alpha': 1.1537401899166926, 'reg_lambda': 2.140944756416896}. Best is trial 4 with value: 0.8310901749663526.
[I 2023-07-06 05:26:53,946] Trial 7 finished with value: 0.5563486913259788 and parameters: {'learning_rate': 0.02046710075633703, 'n_estimators': 312, 'colsample_bytree': 0.8025799086836968, 'subsample': 0.5710777399429426, 'reg_alpha': 3.424732965721752, 'reg_lambda': 1.7616310325718232}. Best is trial 4 with value: 0.8310901749663526.
[I 2023-07-06 05:27:23,611] Trial 8 finished with value: 0.4089275014979029 and parameters: {'learning_rate': 0.002134351994605946, 'n_estimators': 576, 'colsample_bytree': 0.6574551534352904, 'subsample': 0.8514441773938, 'reg_alpha': 0.6611581476272604, 'reg_lambda': 0.3367074235617945}. Best is trial 4 with value: 0.8310901749663526.
[I 2023-07-06 05:28:41,980] Trial 9 finished with value: 0.859228362877998 and parameters: {'learning_rate': 0.08520967733552713, 'n_estimators': 1595, 'colsample_bytree': 0.8305401719936001, 'subsample': 0.7641640601809178, 'reg_alpha': 1.4614539781859777, 'reg_lambda': 1.5002184514029064}. Best is trial 9 with value: 0.859228362877998.

Best trial : score 0.859228362877998,
params {'learning_rate': 0.08520967733552713, 'n_estimators': 1595, 'colsample_bytree': 0.8305401719936001, 'subsample': 0.7641640601809178, 'reg_alpha': 1.4614539781859777, 'reg_lambda': 1.5002184514029064}

1it [09:23, 563.38s/it][I 2023-07-06 05:30:06,040] A new study created in memory with name: no-name-8d66db09-7656-4cfe-a8f5-1d17089aae0e
[I 2023-07-06 05:30:55,196] Trial 0 finished with value: 0.7927750410509029 and parameters: {'learning_rate': 0.05155075222533945, 'n_estimators': 1021, 'colsample_bytree': 0.719350443033115, 'subsample': 0.8026671775328005, 'reg_alpha': 2.929838278776278, 'reg_lambda': 4.381363801434478}. Best is trial 0 with value: 0.7927750410509029.
[I 2023-07-06 05:31:21,203] Trial 1 finished with value: 0.6728378735784183 and parameters: {'learning_rate': 0.03335122173910602, 'n_estimators': 449, 'colsample_bytree': 0.8939597454392421, 'subsample': 0.90185383175199, 'reg_alpha': 0.8325287193873104, 'reg_lambda': 4.1249853208318505}. Best is trial 0 with value: 0.7927750410509029.
[I 2023-07-06 05:31:46,588] Trial 2 finished with value: 0.7118932727788816 and parameters: {'learning_rate': 0.04819051340299198, 'n_estimators': 426, 'colsample_bytree': 0.8867573880389659, 'subsample': 0.7986835712080858, 'reg_alpha': 1.4341480205048074, 'reg_lambda': 4.11778941543427}. Best is trial 0 with value: 0.7927750410509029.
[I 2023-07-06 05:33:16,930] Trial 3 finished with value: 0.8112504235852255 and parameters: {'learning_rate': 0.049031124189119285, 'n_estimators': 1789, 'colsample_bytree': 0.5354452465687923, 'subsample': 0.6551634914707407, 'reg_alpha': 4.443349592067058, 'reg_lambda': 3.275406024914261}. Best is trial 3 with value: 0.8112504235852255.
[I 2023-07-06 05:34:24,754] Trial 4 finished with value: 0.8192934782608696 and parameters: {'learning_rate': 0.06022017902190689, 'n_estimators': 1492, 'colsample_bytree': 0.6792704767870048, 'subsample': 0.5551904219339706, 'reg_alpha': 4.8168769859021126, 'reg_lambda': 2.278705614545406}. Best is trial 4 with value: 0.8192934782608696.
[I 2023-07-06 05:34:48,302] Trial 5 finished with value: 0.7801463569837735 and parameters: {'learning_rate': 0.08609403225492421, 'n_estimators': 482, 'colsample_bytree': 0.6371508281671892, 'subsample': 0.7335093601899446, 'reg_alpha': 2.774451765836108, 'reg_lambda': 2.5463458419800755}. Best is trial 4 with value: 0.8192934782608696.
[I 2023-07-06 05:35:28,991] Trial 6 finished with value: 0.4846671652954376 and parameters: {'learning_rate': 0.0052700473338712, 'n_estimators': 748, 'colsample_bytree': 0.9391703358009253, 'subsample': 0.9307535035437619, 'reg_alpha': 1.1537401899166926, 'reg_lambda': 2.140944756416896}. Best is trial 4 with value: 0.8192934782608696.
[I 2023-07-06 05:35:48,921] Trial 7 finished with value: 0.5554588951718138 and parameters: {'learning_rate': 0.02046710075633703, 'n_estimators': 312, 'colsample_bytree': 0.8025799086836968, 'subsample': 0.5710777399429426, 'reg_alpha': 3.424732965721752, 'reg_lambda': 1.7616310325718232}. Best is trial 4 with value: 0.8192934782608696.
[I 2023-07-06 05:36:17,526] Trial 8 finished with value: 0.41131900417504247 and parameters: {'learning_rate': 0.002134351994605946, 'n_estimators': 576, 'colsample_bytree': 0.6574551534352904, 'subsample': 0.8514441773938, 'reg_alpha': 0.6611581476272604, 'reg_lambda': 0.3367074235617945}. Best is trial 4 with value: 0.8192934782608696.
[I 2023-07-06 05:37:31,854] Trial 9 finished with value: 0.8421797593772116 and parameters: {'learning_rate': 0.08520967733552713, 'n_estimators': 1595, 'colsample_bytree': 0.8305401719936001, 'subsample': 0.7641640601809178, 'reg_alpha': 1.4614539781859777, 'reg_lambda': 1.5002184514029064}. Best is trial 9 with value: 0.8421797593772116.

Best trial : score 0.8421797593772116,
params {'learning_rate': 0.08520967733552713, 'n_estimators': 1595, 'colsample_bytree': 0.8305401719936001, 'subsample': 0.7641640601809178, 'reg_alpha': 1.4614539781859777, 'reg_lambda': 1.5002184514029064}

2it [18:13, 543.53s/it][I 2023-07-06 05:38:55,801] A new study created in memory with name: no-name-d533a1ad-eccc-41f6-8f93-38eeb597ad76
[I 2023-07-06 05:39:45,749] Trial 0 finished with value: 0.8118939883645767 and parameters: {'learning_rate': 0.05155075222533945, 'n_estimators': 1021, 'colsample_bytree': 0.719350443033115, 'subsample': 0.8026671775328005, 'reg_alpha': 2.929838278776278, 'reg_lambda': 4.381363801434478}. Best is trial 0 with value: 0.8118939883645767.
[I 2023-07-06 05:40:11,787] Trial 1 finished with value: 0.6844723749672689 and parameters: {'learning_rate': 0.03335122173910602, 'n_estimators': 449, 'colsample_bytree': 0.8939597454392421, 'subsample': 0.90185383175199, 'reg_alpha': 0.8325287193873104, 'reg_lambda': 4.1249853208318505}. Best is trial 0 with value: 0.8118939883645767.
[I 2023-07-06 05:40:36,153] Trial 2 finished with value: 0.7326732673267328 and parameters: {'learning_rate': 0.04819051340299198, 'n_estimators': 426, 'colsample_bytree': 0.8867573880389659, 'subsample': 0.7986835712080858, 'reg_alpha': 1.4341480205048074, 'reg_lambda': 4.11778941543427}. Best is trial 0 with value: 0.8118939883645767.
[I 2023-07-06 05:42:06,201] Trial 3 finished with value: 0.8330534094726234 and parameters: {'learning_rate': 0.049031124189119285, 'n_estimators': 1789, 'colsample_bytree': 0.5354452465687923, 'subsample': 0.6551634914707407, 'reg_alpha': 4.443349592067058, 'reg_lambda': 3.275406024914261}. Best is trial 3 with value: 0.8330534094726234.
[I 2023-07-06 05:43:16,287] Trial 4 finished with value: 0.8354089532144059 and parameters: {'learning_rate': 0.06022017902190689, 'n_estimators': 1492, 'colsample_bytree': 0.6792704767870048, 'subsample': 0.5551904219339706, 'reg_alpha': 4.8168769859021126, 'reg_lambda': 2.278705614545406}. Best is trial 4 with value: 0.8354089532144059.
[I 2023-07-06 05:43:37,364] Trial 5 finished with value: 0.7918495297805642 and parameters: {'learning_rate': 0.08609403225492421, 'n_estimators': 482, 'colsample_bytree': 0.6371508281671892, 'subsample': 0.7335093601899446, 'reg_alpha': 2.774451765836108, 'reg_lambda': 2.5463458419800755}. Best is trial 4 with value: 0.8354089532144059.
[I 2023-07-06 05:44:25,002] Trial 6 finished with value: 0.49367088607594944 and parameters: {'learning_rate': 0.0052700473338712, 'n_estimators': 748, 'colsample_bytree': 0.9391703358009253, 'subsample': 0.9307535035437619, 'reg_alpha': 1.1537401899166926, 'reg_lambda': 2.140944756416896}. Best is trial 4 with value: 0.8354089532144059.
[I 2023-07-06 05:44:42,658] Trial 7 finished with value: 0.5708678587003925 and parameters: {'learning_rate': 0.02046710075633703, 'n_estimators': 312, 'colsample_bytree': 0.8025799086836968, 'subsample': 0.5710777399429426, 'reg_alpha': 3.424732965721752, 'reg_lambda': 1.7616310325718232}. Best is trial 4 with value: 0.8354089532144059.
[I 2023-07-06 05:45:10,942] Trial 8 finished with value: 0.40498723148565424 and parameters: {'learning_rate': 0.002134351994605946, 'n_estimators': 576, 'colsample_bytree': 0.6574551534352904, 'subsample': 0.8514441773938, 'reg_alpha': 0.6611581476272604, 'reg_lambda': 0.3367074235617945}. Best is trial 4 with value: 0.8354089532144059.
[I 2023-07-06 05:46:22,973] Trial 9 finished with value: 0.8551628551628552 and parameters: {'learning_rate': 0.08520967733552713, 'n_estimators': 1595, 'colsample_bytree': 0.8305401719936001, 'subsample': 0.7641640601809178, 'reg_alpha': 1.4614539781859777, 'reg_lambda': 1.5002184514029064}. Best is trial 9 with value: 0.8551628551628552.

Best trial : score 0.8551628551628552,
params {'learning_rate': 0.08520967733552713, 'n_estimators': 1595, 'colsample_bytree': 0.8305401719936001, 'subsample': 0.7641640601809178, 'reg_alpha': 1.4614539781859777, 'reg_lambda': 1.5002184514029064}

3it [27:00, 536.35s/it][I 2023-07-06 05:47:43,497] A new study created in memory with name: no-name-185489e8-de7d-40af-8f31-b851b1663856
[I 2023-07-06 05:48:35,457] Trial 0 finished with value: 0.8070634401569654 and parameters: {'learning_rate': 0.05155075222533945, 'n_estimators': 1021, 'colsample_bytree': 0.719350443033115, 'subsample': 0.8026671775328005, 'reg_alpha': 2.929838278776278, 'reg_lambda': 4.381363801434478}. Best is trial 0 with value: 0.8070634401569654.
[I 2023-07-06 05:49:00,171] Trial 1 finished with value: 0.6864157993061116 and parameters: {'learning_rate': 0.03335122173910602, 'n_estimators': 449, 'colsample_bytree': 0.8939597454392421, 'subsample': 0.90185383175199, 'reg_alpha': 0.8325287193873104, 'reg_lambda': 4.1249853208318505}. Best is trial 0 with value: 0.8070634401569654.
[I 2023-07-06 05:49:24,272] Trial 2 finished with value: 0.7240491850157278 and parameters: {'learning_rate': 0.04819051340299198, 'n_estimators': 426, 'colsample_bytree': 0.8867573880389659, 'subsample': 0.7986835712080858, 'reg_alpha': 1.4341480205048074, 'reg_lambda': 4.11778941543427}. Best is trial 0 with value: 0.8070634401569654.
[I 2023-07-06 05:50:45,002] Trial 3 finished with value: 0.8248125426039538 and parameters: {'learning_rate': 0.049031124189119285, 'n_estimators': 1789, 'colsample_bytree': 0.5354452465687923, 'subsample': 0.6551634914707407, 'reg_alpha': 4.443349592067058, 'reg_lambda': 3.275406024914261}. Best is trial 3 with value: 0.8248125426039538.
[I 2023-07-06 05:51:53,370] Trial 4 finished with value: 0.8279863481228669 and parameters: {'learning_rate': 0.06022017902190689, 'n_estimators': 1492, 'colsample_bytree': 0.6792704767870048, 'subsample': 0.5551904219339706, 'reg_alpha': 4.8168769859021126, 'reg_lambda': 2.278705614545406}. Best is trial 4 with value: 0.8279863481228669.
[I 2023-07-06 05:52:19,249] Trial 5 finished with value: 0.7869481765834933 and parameters: {'learning_rate': 0.08609403225492421, 'n_estimators': 482, 'colsample_bytree': 0.6371508281671892, 'subsample': 0.7335093601899446, 'reg_alpha': 2.774451765836108, 'reg_lambda': 2.5463458419800755}. Best is trial 4 with value: 0.8279863481228669.
[I 2023-07-06 05:53:03,023] Trial 6 finished with value: 0.4976887519260401 and parameters: {'learning_rate': 0.0052700473338712, 'n_estimators': 748, 'colsample_bytree': 0.9391703358009253, 'subsample': 0.9307535035437619, 'reg_alpha': 1.1537401899166926, 'reg_lambda': 2.140944756416896}. Best is trial 4 with value: 0.8279863481228669.
[I 2023-07-06 05:53:21,628] Trial 7 finished with value: 0.5781249999999999 and parameters: {'learning_rate': 0.02046710075633703, 'n_estimators': 312, 'colsample_bytree': 0.8025799086836968, 'subsample': 0.5710777399429426, 'reg_alpha': 3.424732965721752, 'reg_lambda': 1.7616310325718232}. Best is trial 4 with value: 0.8279863481228669.
[I 2023-07-06 05:53:49,796] Trial 8 finished with value: 0.4127082048118445 and parameters: {'learning_rate': 0.002134351994605946, 'n_estimators': 576, 'colsample_bytree': 0.6574551534352904, 'subsample': 0.8514441773938, 'reg_alpha': 0.6611581476272604, 'reg_lambda': 0.3367074235617945}. Best is trial 4 with value: 0.8279863481228669.
[I 2023-07-06 05:55:03,156] Trial 9 finished with value: 0.8495575221238938 and parameters: {'learning_rate': 0.08520967733552713, 'n_estimators': 1595, 'colsample_bytree': 0.8305401719936001, 'subsample': 0.7641640601809178, 'reg_alpha': 1.4614539781859777, 'reg_lambda': 1.5002184514029064}. Best is trial 9 with value: 0.8495575221238938.

Best trial : score 0.8495575221238938,
params {'learning_rate': 0.08520967733552713, 'n_estimators': 1595, 'colsample_bytree': 0.8305401719936001, 'subsample': 0.7641640601809178, 'reg_alpha': 1.4614539781859777, 'reg_lambda': 1.5002184514029064}

4it [35:44, 531.42s/it][I 2023-07-06 05:56:27,337] A new study created in memory with name: no-name-a8aecd60-1e18-4a06-8f38-52e8bc8f32df
[I 2023-07-06 05:57:17,178] Trial 0 finished with value: 0.7968800779980499 and parameters: {'learning_rate': 0.05155075222533945, 'n_estimators': 1021, 'colsample_bytree': 0.719350443033115, 'subsample': 0.8026671775328005, 'reg_alpha': 2.929838278776278, 'reg_lambda': 4.381363801434478}. Best is trial 0 with value: 0.7968800779980499.
[I 2023-07-06 05:57:43,004] Trial 1 finished with value: 0.6678870292887029 and parameters: {'learning_rate': 0.03335122173910602, 'n_estimators': 449, 'colsample_bytree': 0.8939597454392421, 'subsample': 0.90185383175199, 'reg_alpha': 0.8325287193873104, 'reg_lambda': 4.1249853208318505}. Best is trial 0 with value: 0.7968800779980499.
[I 2023-07-06 05:58:06,090] Trial 2 finished with value: 0.711864406779661 and parameters: {'learning_rate': 0.04819051340299198, 'n_estimators': 426, 'colsample_bytree': 0.8867573880389659, 'subsample': 0.7986835712080858, 'reg_alpha': 1.4341480205048074, 'reg_lambda': 4.11778941543427}. Best is trial 0 with value: 0.7968800779980499.
[I 2023-07-06 05:59:35,827] Trial 3 finished with value: 0.8196065355118373 and parameters: {'learning_rate': 0.049031124189119285, 'n_estimators': 1789, 'colsample_bytree': 0.5354452465687923, 'subsample': 0.6551634914707407, 'reg_alpha': 4.443349592067058, 'reg_lambda': 3.275406024914261}. Best is trial 3 with value: 0.8196065355118373.
[I 2023-07-06 06:00:46,070] Trial 4 finished with value: 0.8245555182824555 and parameters: {'learning_rate': 0.06022017902190689, 'n_estimators': 1492, 'colsample_bytree': 0.6792704767870048, 'subsample': 0.5551904219339706, 'reg_alpha': 4.8168769859021126, 'reg_lambda': 2.278705614545406}. Best is trial 4 with value: 0.8245555182824555.
[I 2023-07-06 06:01:09,825] Trial 5 finished with value: 0.7852604828462516 and parameters: {'learning_rate': 0.08609403225492421, 'n_estimators': 482, 'colsample_bytree': 0.6371508281671892, 'subsample': 0.7335093601899446, 'reg_alpha': 2.774451765836108, 'reg_lambda': 2.5463458419800755}. Best is trial 4 with value: 0.8245555182824555.
[I 2023-07-06 06:01:52,740] Trial 6 finished with value: 0.4831964152352502 and parameters: {'learning_rate': 0.0052700473338712, 'n_estimators': 748, 'colsample_bytree': 0.9391703358009253, 'subsample': 0.9307535035437619, 'reg_alpha': 1.1537401899166926, 'reg_lambda': 2.140944756416896}. Best is trial 4 with value: 0.8245555182824555.
[I 2023-07-06 06:02:12,887] Trial 7 finished with value: 0.5539987066178056 and parameters: {'learning_rate': 0.02046710075633703, 'n_estimators': 312, 'colsample_bytree': 0.8025799086836968, 'subsample': 0.5710777399429426, 'reg_alpha': 3.424732965721752, 'reg_lambda': 1.7616310325718232}. Best is trial 4 with value: 0.8245555182824555.
[I 2023-07-06 06:02:41,349] Trial 8 finished with value: 0.4051632498101747 and parameters: {'learning_rate': 0.002134351994605946, 'n_estimators': 576, 'colsample_bytree': 0.6574551534352904, 'subsample': 0.8514441773938, 'reg_alpha': 0.6611581476272604, 'reg_lambda': 0.3367074235617945}. Best is trial 4 with value: 0.8245555182824555.
[I 2023-07-06 06:03:55,008] Trial 9 finished with value: 0.8512998266897747 and parameters: {'learning_rate': 0.08520967733552713, 'n_estimators': 1595, 'colsample_bytree': 0.8305401719936001, 'subsample': 0.7641640601809178, 'reg_alpha': 1.4614539781859777, 'reg_lambda': 1.5002184514029064}. Best is trial 9 with value: 0.8512998266897747.

Best trial : score 0.8512998266897747,
params {'learning_rate': 0.08520967733552713, 'n_estimators': 1595, 'colsample_bytree': 0.8305401719936001, 'subsample': 0.7641640601809178, 'reg_alpha': 1.4614539781859777, 'reg_lambda': 1.5002184514029064}

5it [44:38, 535.65s/it]

#부산

In [ ]:
import pandas as pd
busan = pd.read_csv('/content/gdrive/MyDrive/2023날씨빅콘/final_data/final_csv/가까운거리/부산_가까운거리_train_최종.csv',index_col=0)
busan

,busan_drag_train_final.num,busan_drag_train_final.time,busan_drag_train_final.latitude,busan_drag_train_final.longitude,busan_drag_train_final.sog,busan_drag_train_final.cog,busan_drag_train_final.hdg,stn_num,target,kma_pagobuoy_train.stn_name,...,kma_pagobuoy_train.sig_wh,kma_pagobuoy_train.mean_wh,khoa_buoy_train.stn_name,khoa_buoy_train.ws,khoa_buoy_train.wd_point,khoa_buoy_train.wd,kma_lightbecon_train.stn_name,kma_lightbecon_train.stn,kma_lightbecon_train.wd,kma_lightbecon_train.ws
404,1,2021-01-16 09:41:00,"""N35.049383""","""E129.073848""",0.3,239.2,0.0,N3,0,오륙도,...,0.3,0.2,Haeundae,21.75,E,91.5,Oryuk Island,984.0,297.0,4.9
465,1,2021-01-16 15:14:00,"""N35.049533""","""E129.074067""",0.1,218.4,59.0,N3,0,오륙도,...,0.4,0.3,Haeundae,32.75,E,88.0,Oryuk Island,984.0,282.0,7.3
466,1,2021-01-16 15:14:00,"""N35.049533""","""E129.074067""",0.2,218.3,60.0,N3,0,오륙도,...,0.4,0.3,Haeundae,32.75,E,88.0,Oryuk Island,984.0,282.0,7.3
535,1,2021-01-16 22:17:00,"""N35.048995""","""E129.073660""",0.2,98.6,45.0,N3,0,오륙도,...,0.4,0.3,Haeundae,9.50,E,95.5,Oryuk Island,984.0,306.0,9.3
696,3,2021-01-17 02:05:00,"""N35.006715""","""E129.063955""",0.5,309.8,4.0,N5,0,다대포,...,0.3,0.2,Haeundae,20.00,E,95.5,Oryuk Island,984.0,296.0,6.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
294228,1160,2022-04-10 17:36:26,"""N35.048752""","""E129.042125""",0.1,125.3,222.0,N3,0,다대포,...,0.5,0.3,Haeundae,19.10,ENE,71.0,Oryuk Island,984.0,198.0,10.1
294229,1160,2022-04-10 17:39:26,"""N35.048738""","""E129.042160""",0.1,149.6,223.0,N3,0,다대포,...,0.5,0.3,Haeundae,16.90,ENE,61.0,Oryuk Island,984.0,196.0,10.6
294230,1160,2022-04-10 17:45:26,"""N35.048702""","""E129.042170""",0.1,152.4,223.0,N3,0,다대포,...,0.5,0.3,Haeundae,18.20,ENE,73.0,Oryuk Island,984.0,195.0,9.2
294231,1160,2022-04-10 17:48:26,"""N35.048752""","""E129.042160""",0.1,172.6,223.0,N3,0,다대포,...,0.5,0.3,Haeundae,15.90,ENE,73.0,Oryuk Island,984.0,196.0,9.4
294232,1160,2022-04-10 17:51:26,"""N35.048700""","""E129.042158""",0.0,148.1,222.0,N3,0,다대포,...,0.5,0.3,Haeundae,19.50,ENE,78.0,Oryuk Island,984.0,199.0,8.3

In [ ]:
busan_test = pd.read_csv('/content/gdrive/MyDrive/2023날씨빅콘/final_data/final_csv/가까운거리/부산_가까운거리_test_최종.csv',index_col=0)
busan_test

,busan_anch_drag_test.area,busan_anch_drag_test.time,busan_anch_drag_test.num,busan_anch_drag_test.lat,busan_anch_drag_test.lon,busan_anch_drag_test.sog,busan_anch_drag_test.cog,busan_anch_drag_test.hdg,stn_num,kma_pagobuoy_test.stn_name,...,kma_pagobuoy_test.sig_wh,kma_pagobuoy_test.mean_wh,khoa_buoy_test.stn_name,khoa_buoy_test.ws,khoa_buoy_test.wd_point,khoa_buoy_test.wd,kma_lightbecon_test.stn_name,kma_lightbecon_test.stn,kma_lightbecon_test.wd,kma_lightbecon_test.ws
0,"""BUSAN""",2022-08-14 00:55:06,1001,"""N35.052557""","""E129.040953""",0.2,222.8,158.0,N3,다대포,...,0.6,0.4,Haeundae,20.4,ENE,69.0,Oryuk Island,984.0,229.0,6.7
1,"""BUSAN""",2022-08-14 00:55:16,1001,"""N35.052587""","""E129.041017""",0.1,162.3,72.0,N3,다대포,...,0.6,0.4,Haeundae,20.4,ENE,69.0,Oryuk Island,984.0,229.0,6.7
2,"""BUSAN""",2022-08-14 00:55:24,1001,"""N35.052625""","""E129.041087""",0.1,162.3,72.0,N3,다대포,...,0.6,0.4,Haeundae,20.4,ENE,69.0,Oryuk Island,984.0,229.0,6.7
3,"""BUSAN""",2022-08-14 00:55:36,1001,"""N35.052680""","""E129.041187""",0.1,40.0,118.0,N3,다대포,...,0.6,0.4,Haeundae,20.4,ENE,69.0,Oryuk Island,984.0,229.0,6.7
4,"""BUSAN""",2022-08-14 00:55:45,1001,"""N35.052732""","""E129.041275""",0.1,127.1,197.0,N3,다대포,...,0.6,0.4,Haeundae,20.4,ENE,69.0,Oryuk Island,984.0,229.0,6.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153294,"""BUSAN""",2023-03-08 11:01:43,1116,"""N35.021717""","""E129.065633""",0.4,157.0,220.0,N5,오륙도,...,0.5,0.3,Haeundae,37.5,ESE,106.0,Oryuk Island,984.0,229.0,6.2
153295,"""BUSAN""",2023-03-08 11:02:04,1116,"""N35.021667""","""E129.065650""",0.4,153.0,219.0,N5,오륙도,...,0.5,0.3,Haeundae,38.1,ESE,110.0,Oryuk Island,984.0,225.0,6.2
153296,"""BUSAN""",2023-03-08 11:02:12,1116,"""N35.021650""","""E129.065667""",0.4,150.0,219.0,N5,오륙도,...,0.5,0.3,Haeundae,38.1,ESE,110.0,Oryuk Island,984.0,225.0,6.2
153297,"""BUSAN""",2023-03-08 11:02:22,1116,"""N35.021617""","""E129.065683""",0.4,148.0,218.0,N5,오륙도,...,0.5,0.3,Haeundae,38.1,ESE,110.0,Oryuk Island,984.0,225.0,6.2
153298,"""BUSAN""",2023-03-08 11:02:54,1116,"""N35.021550""","""E129.065733""",0.5,142.0,217.0,N5,오륙도,...,0.5,0.3,Haeundae,38.1,ESE,110.0,Oryuk Island,984.0,225.0,6.2

## 전처리

In [ ]:
busan = busan.drop(columns=['busan_drag_train_final.num', 'busan_drag_train_final.time','busan_drag_train_final.latitude', 'busan_drag_train_final.longitude',
                            'kma_pagobuoy_train.stn_name', 'kma_pagobuoy_train.stn', 'khoa_buoy_train.stn_name',
                            'kma_lightbecon_train.stn_name', 'kma_lightbecon_train.stn','kma_pagobuoy_train.max_wh',
                            'kma_pagobuoy_train.mean_wh','khoa_buoy_train.wd_point'])

In [ ]:
busan_test = busan_test.drop(columns=['busan_anch_drag_test.area', 'busan_anch_drag_test.time','busan_anch_drag_test.num', 'busan_anch_drag_test.lat',
                                      'busan_anch_drag_test.lon','kma_pagobuoy_test.stn_name', 'kma_pagobuoy_test.stn','khoa_buoy_test.stn_name',
                                      'kma_lightbecon_test.stn_name', 'kma_lightbecon_test.stn','kma_pagobuoy_test.max_wh','kma_pagobuoy_test.mean_wh',
                                      'khoa_buoy_test.wd_point'])

In [ ]:
busan.columns = ['busan_anch_drag_test.sog', 'busan_anch_drag_test.cog',
       'busan_anch_drag_test.hdg', 'stn_num','target',
       'kma_pagobuoy_test.sig_wh',
       'khoa_buoy_test.ws','khoa_buoy_test.wd',
       'kma_lightbecon_test.wd', 'kma_lightbecon_test.ws']

In [ ]:
busan = busan[busan['stn_num']!= 'outlier']

In [ ]:
feature = ['busan_anch_drag_test.sog', 'busan_anch_drag_test.cog',
       'busan_anch_drag_test.hdg', 'stn_num',
       'kma_pagobuoy_test.sig_wh',
       'khoa_buoy_test.ws','khoa_buoy_test.wd',
       'kma_lightbecon_test.wd', 'kma_lightbecon_test.ws']

In [ ]:
from sklearn.preprocessing import LabelEncoder
le_busan = LabelEncoder()
le_busan=le_busan.fit(busan['stn_num'])
busan['stn_num']=le_busan.transform(busan['stn_num'])
busan_test['stn_num']=le_busan.transform(busan_test['stn_num'])

In [ ]:
from lightgbm.sklearn import LGBMClassifier
import optuna
from lightgbm import LGBMRegressor, Dataset
from optuna.samplers import TPESampler
from sklearn.model_selection import StratifiedKFold, KFold
from imblearn.over_sampling import SMOTE
from optuna.samplers import TPESampler
from sklearn.metrics import f1_score
from tqdm import tqdm
import warnings
warnings.filterwarnings('ignore')


test_x = busan_test[feature]

busan_preds = []
kf = StratifiedKFold(n_splits=5, shuffle=True, random_state=seed)

for f, (train_idx, val_idx) in tqdm(enumerate(kf.split(range(len(busan)), y=busan['target']))):
    train_x = busan[feature].iloc[train_idx]
    valid_x = busan[feature].iloc[val_idx]
    y_train = busan[y_feature].iloc[train_idx]
    y_valid = busan[y_feature].iloc[val_idx]


    #sm = SMOTENC(categorical_features=[3], random_state=seed)
    #train_x, y_train = sm.fit_resample(train_x, y_train)
    sm = SMOTE(sampling_strategy=1)
    train_x, y_train = sm.fit_resample(train_x, y_train)

    #sm = RandomUnderSampler()
    #train_x, y_train = sm.fit_resample(train_x, y_train)

    preds = []
    train_y = y_train[y_feature]
    valid_y = y_valid[y_feature]

    sampler = TPESampler(seed=seed)

    def objective(trial):

            param = {
                'random_state': seed,
                'metric'    : 'logloss',
                #'max_depth' : trial.suggest_int('max_depth', 10, 20),
                'max_depth' : -1,
                'learning_rate': trial.suggest_float('learning_rate', 1e-3, 0.1),
                'n_estimators': trial.suggest_int('n_estimators', 100, 2000),
                #'num_leaves'  : trial.suggest_int('num_leaves', 31, 1024),
                'num_leaves' : 31,
                'colsample_bytree' : trial.suggest_float('colsample_bytree', 0.5, 1.0),
                'subsample' :trial.suggest_float('subsample', 0.5, 1.0),
                'reg_alpha' : trial.suggest_float('reg_alpha', 0.0, 5.0),
                'reg_lambda' : trial.suggest_float('reg_lambda', 0.0, 5.0),
                'n_jobs' : -1,
                'boost_from_average' : False
            }

            model = LGBMClassifier(**param)
            model.fit(train_x, y_train, eval_set=[(valid_x, y_valid)], eval_metric = 'logloss', verbose=0)

            y_valid_pred = model.predict(valid_x)
            return f1_score(y_valid, y_valid_pred)

    study = optuna.create_study(direction='maximize', sampler=sampler)
    study.optimize(objective, n_trials=10)

    print('Best trial : score {}, \nparams {}'.format(study.best_trial.value, study.best_trial.params))

    model = LGBMClassifier(**study.best_params, random_state=seed, metric='logloss', n_jobs=-1)
    model.fit(train_x, train_y, eval_set=[(valid_x, valid_y)], eval_metric = 'logloss', verbose=0)

    #pred = model.predict(test_x)
    pred = model.predict_proba(test_x)[:,1]
    preds.append(pred)
    busan_preds.append(preds)

0it [00:00, ?it/s][I 2023-07-06 06:05:26,876] A new study created in memory with name: no-name-2440e745-43e8-404c-8340-92a3fdc42166
[I 2023-07-06 06:06:02,647] Trial 0 finished with value: 0.905646630236794 and parameters: {'learning_rate': 0.05155075222533945, 'n_estimators': 1021, 'colsample_bytree': 0.719350443033115, 'subsample': 0.8026671775328005, 'reg_alpha': 2.929838278776278, 'reg_lambda': 4.381363801434478}. Best is trial 0 with value: 0.905646630236794.
[I 2023-07-06 06:06:22,395] Trial 1 finished with value: 0.7731926776295377 and parameters: {'learning_rate': 0.03335122173910602, 'n_estimators': 449, 'colsample_bytree': 0.8939597454392421, 'subsample': 0.90185383175199, 'reg_alpha': 0.8325287193873104, 'reg_lambda': 4.1249853208318505}. Best is trial 0 with value: 0.905646630236794.
[I 2023-07-06 06:06:39,251] Trial 2 finished with value: 0.8141130349558968 and parameters: {'learning_rate': 0.04819051340299198, 'n_estimators': 426, 'colsample_bytree': 0.8867573880389659, 'subsample': 0.7986835712080858, 'reg_alpha': 1.4341480205048074, 'reg_lambda': 4.11778941543427}. Best is trial 0 with value: 0.905646630236794.
[I 2023-07-06 06:07:50,206] Trial 3 finished with value: 0.9301277235161532 and parameters: {'learning_rate': 0.049031124189119285, 'n_estimators': 1789, 'colsample_bytree': 0.5354452465687923, 'subsample': 0.6551634914707407, 'reg_alpha': 4.443349592067058, 'reg_lambda': 3.275406024914261}. Best is trial 3 with value: 0.9301277235161532.
[I 2023-07-06 06:08:45,095] Trial 4 finished with value: 0.93293142426526 and parameters: {'learning_rate': 0.06022017902190689, 'n_estimators': 1492, 'colsample_bytree': 0.6792704767870048, 'subsample': 0.5551904219339706, 'reg_alpha': 4.8168769859021126, 'reg_lambda': 2.278705614545406}. Best is trial 4 with value: 0.93293142426526.
[I 2023-07-06 06:09:03,035] Trial 5 finished with value: 0.8896057347670251 and parameters: {'learning_rate': 0.08609403225492421, 'n_estimators': 482, 'colsample_bytree': 0.6371508281671892, 'subsample': 0.7335093601899446, 'reg_alpha': 2.774451765836108, 'reg_lambda': 2.5463458419800755}. Best is trial 4 with value: 0.93293142426526.
[I 2023-07-06 06:09:34,065] Trial 6 finished with value: 0.5408229915088177 and parameters: {'learning_rate': 0.0052700473338712, 'n_estimators': 748, 'colsample_bytree': 0.9391703358009253, 'subsample': 0.9307535035437619, 'reg_alpha': 1.1537401899166926, 'reg_lambda': 2.140944756416896}. Best is trial 4 with value: 0.93293142426526.
[I 2023-07-06 06:09:48,205] Trial 7 finished with value: 0.6401857106009802 and parameters: {'learning_rate': 0.02046710075633703, 'n_estimators': 312, 'colsample_bytree': 0.8025799086836968, 'subsample': 0.5710777399429426, 'reg_alpha': 3.424732965721752, 'reg_lambda': 1.7616310325718232}. Best is trial 4 with value: 0.93293142426526.
[I 2023-07-06 06:10:11,841] Trial 8 finished with value: 0.39678972712680577 and parameters: {'learning_rate': 0.002134351994605946, 'n_estimators': 576, 'colsample_bytree': 0.6574551534352904, 'subsample': 0.8514441773938, 'reg_alpha': 0.6611581476272604, 'reg_lambda': 0.3367074235617945}. Best is trial 4 with value: 0.93293142426526.
[I 2023-07-06 06:11:11,216] Trial 9 finished with value: 0.9558879938626775 and parameters: {'learning_rate': 0.08520967733552713, 'n_estimators': 1595, 'colsample_bytree': 0.8305401719936001, 'subsample': 0.7641640601809178, 'reg_alpha': 1.4614539781859777, 'reg_lambda': 1.5002184514029064}. Best is trial 9 with value: 0.9558879938626775.

Best trial : score 0.9558879938626775,
params {'learning_rate': 0.08520967733552713, 'n_estimators': 1595, 'colsample_bytree': 0.8305401719936001, 'subsample': 0.7641640601809178, 'reg_alpha': 1.4614539781859777, 'reg_lambda': 1.5002184514029064}

1it [06:51, 411.26s/it][I 2023-07-06 06:12:18,021] A new study created in memory with name: no-name-123b769f-014f-4575-81ca-e0d92ebf9079
[I 2023-07-06 06:12:59,765] Trial 0 finished with value: 0.9080162541558923 and parameters: {'learning_rate': 0.05155075222533945, 'n_estimators': 1021, 'colsample_bytree': 0.719350443033115, 'subsample': 0.8026671775328005, 'reg_alpha': 2.929838278776278, 'reg_lambda': 4.381363801434478}. Best is trial 0 with value: 0.9080162541558923.
[I 2023-07-06 06:13:18,825] Trial 1 finished with value: 0.7698042870456664 and parameters: {'learning_rate': 0.03335122173910602, 'n_estimators': 449, 'colsample_bytree': 0.8939597454392421, 'subsample': 0.90185383175199, 'reg_alpha': 0.8325287193873104, 'reg_lambda': 4.1249853208318505}. Best is trial 0 with value: 0.9080162541558923.
[I 2023-07-06 06:13:36,287] Trial 2 finished with value: 0.8098199672667759 and parameters: {'learning_rate': 0.04819051340299198, 'n_estimators': 426, 'colsample_bytree': 0.8867573880389659, 'subsample': 0.7986835712080858, 'reg_alpha': 1.4341480205048074, 'reg_lambda': 4.11778941543427}. Best is trial 0 with value: 0.9080162541558923.
[I 2023-07-06 06:14:45,165] Trial 3 finished with value: 0.9275471698113207 and parameters: {'learning_rate': 0.049031124189119285, 'n_estimators': 1789, 'colsample_bytree': 0.5354452465687923, 'subsample': 0.6551634914707407, 'reg_alpha': 4.443349592067058, 'reg_lambda': 3.275406024914261}. Best is trial 3 with value: 0.9275471698113207.
[I 2023-07-06 06:15:39,604] Trial 4 finished with value: 0.9337873628452517 and parameters: {'learning_rate': 0.06022017902190689, 'n_estimators': 1492, 'colsample_bytree': 0.6792704767870048, 'subsample': 0.5551904219339706, 'reg_alpha': 4.8168769859021126, 'reg_lambda': 2.278705614545406}. Best is trial 4 with value: 0.9337873628452517.
[I 2023-07-06 06:15:59,574] Trial 5 finished with value: 0.8846431146359048 and parameters: {'learning_rate': 0.08609403225492421, 'n_estimators': 482, 'colsample_bytree': 0.6371508281671892, 'subsample': 0.7335093601899446, 'reg_alpha': 2.774451765836108, 'reg_lambda': 2.5463458419800755}. Best is trial 4 with value: 0.9337873628452517.
[I 2023-07-06 06:16:39,525] Trial 6 finished with value: 0.5465838509316769 and parameters: {'learning_rate': 0.0052700473338712, 'n_estimators': 748, 'colsample_bytree': 0.9391703358009253, 'subsample': 0.9307535035437619, 'reg_alpha': 1.1537401899166926, 'reg_lambda': 2.140944756416896}. Best is trial 4 with value: 0.9337873628452517.
[I 2023-07-06 06:16:53,951] Trial 7 finished with value: 0.6278004073319756 and parameters: {'learning_rate': 0.02046710075633703, 'n_estimators': 312, 'colsample_bytree': 0.8025799086836968, 'subsample': 0.5710777399429426, 'reg_alpha': 3.424732965721752, 'reg_lambda': 1.7616310325718232}. Best is trial 4 with value: 0.9337873628452517.
[I 2023-07-06 06:17:18,670] Trial 8 finished with value: 0.3944255388105655 and parameters: {'learning_rate': 0.002134351994605946, 'n_estimators': 576, 'colsample_bytree': 0.6574551534352904, 'subsample': 0.8514441773938, 'reg_alpha': 0.6611581476272604, 'reg_lambda': 0.3367074235617945}. Best is trial 4 with value: 0.9337873628452517.
[I 2023-07-06 06:18:18,512] Trial 9 finished with value: 0.9543186180422265 and parameters: {'learning_rate': 0.08520967733552713, 'n_estimators': 1595, 'colsample_bytree': 0.8305401719936001, 'subsample': 0.7641640601809178, 'reg_alpha': 1.4614539781859777, 'reg_lambda': 1.5002184514029064}. Best is trial 9 with value: 0.9543186180422265.

Best trial : score 0.9543186180422265,
params {'learning_rate': 0.08520967733552713, 'n_estimators': 1595, 'colsample_bytree': 0.8305401719936001, 'subsample': 0.7641640601809178, 'reg_alpha': 1.4614539781859777, 'reg_lambda': 1.5002184514029064}

2it [14:05, 424.88s/it][I 2023-07-06 06:19:32,443] A new study created in memory with name: no-name-a439b32c-2d2f-408a-ae2f-ddaad321f970
[I 2023-07-06 06:20:10,949] Trial 0 finished with value: 0.9178885630498534 and parameters: {'learning_rate': 0.05155075222533945, 'n_estimators': 1021, 'colsample_bytree': 0.719350443033115, 'subsample': 0.8026671775328005, 'reg_alpha': 2.929838278776278, 'reg_lambda': 4.381363801434478}. Best is trial 0 with value: 0.9178885630498534.
[I 2023-07-06 06:20:29,517] Trial 1 finished with value: 0.776844070961718 and parameters: {'learning_rate': 0.03335122173910602, 'n_estimators': 449, 'colsample_bytree': 0.8939597454392421, 'subsample': 0.90185383175199, 'reg_alpha': 0.8325287193873104, 'reg_lambda': 4.1249853208318505}. Best is trial 0 with value: 0.9178885630498534.
[I 2023-07-06 06:20:51,913] Trial 2 finished with value: 0.822527832351015 and parameters: {'learning_rate': 0.04819051340299198, 'n_estimators': 426, 'colsample_bytree': 0.8867573880389659, 'subsample': 0.7986835712080858, 'reg_alpha': 1.4341480205048074, 'reg_lambda': 4.11778941543427}. Best is trial 0 with value: 0.9178885630498534.
[I 2023-07-06 06:22:01,706] Trial 3 finished with value: 0.9373601789709173 and parameters: {'learning_rate': 0.049031124189119285, 'n_estimators': 1789, 'colsample_bytree': 0.5354452465687923, 'subsample': 0.6551634914707407, 'reg_alpha': 4.443349592067058, 'reg_lambda': 3.275406024914261}. Best is trial 3 with value: 0.9373601789709173.
[I 2023-07-06 06:22:57,141] Trial 4 finished with value: 0.9421857515852294 and parameters: {'learning_rate': 0.06022017902190689, 'n_estimators': 1492, 'colsample_bytree': 0.6792704767870048, 'subsample': 0.5551904219339706, 'reg_alpha': 4.8168769859021126, 'reg_lambda': 2.278705614545406}. Best is trial 4 with value: 0.9421857515852294.
[I 2023-07-06 06:23:14,085] Trial 5 finished with value: 0.8989169675090253 and parameters: {'learning_rate': 0.08609403225492421, 'n_estimators': 482, 'colsample_bytree': 0.6371508281671892, 'subsample': 0.7335093601899446, 'reg_alpha': 2.774451765836108, 'reg_lambda': 2.5463458419800755}. Best is trial 4 with value: 0.9421857515852294.
[I 2023-07-06 06:23:46,478] Trial 6 finished with value: 0.5458947831829187 and parameters: {'learning_rate': 0.0052700473338712, 'n_estimators': 748, 'colsample_bytree': 0.9391703358009253, 'subsample': 0.9307535035437619, 'reg_alpha': 1.1537401899166926, 'reg_lambda': 2.140944756416896}. Best is trial 4 with value: 0.9421857515852294.
[I 2023-07-06 06:24:00,352] Trial 7 finished with value: 0.6403100775193798 and parameters: {'learning_rate': 0.02046710075633703, 'n_estimators': 312, 'colsample_bytree': 0.8025799086836968, 'subsample': 0.5710777399429426, 'reg_alpha': 3.424732965721752, 'reg_lambda': 1.7616310325718232}. Best is trial 4 with value: 0.9421857515852294.
[I 2023-07-06 06:24:23,413] Trial 8 finished with value: 0.4052136611120277 and parameters: {'learning_rate': 0.002134351994605946, 'n_estimators': 576, 'colsample_bytree': 0.6574551534352904, 'subsample': 0.8514441773938, 'reg_alpha': 0.6611581476272604, 'reg_lambda': 0.3367074235617945}. Best is trial 4 with value: 0.9421857515852294.
[I 2023-07-06 06:25:25,073] Trial 9 finished with value: 0.9626808834729627 and parameters: {'learning_rate': 0.08520967733552713, 'n_estimators': 1595, 'colsample_bytree': 0.8305401719936001, 'subsample': 0.7641640601809178, 'reg_alpha': 1.4614539781859777, 'reg_lambda': 1.5002184514029064}. Best is trial 9 with value: 0.9626808834729627.

Best trial : score 0.9626808834729627,
params {'learning_rate': 0.08520967733552713, 'n_estimators': 1595, 'colsample_bytree': 0.8305401719936001, 'subsample': 0.7641640601809178, 'reg_alpha': 1.4614539781859777, 'reg_lambda': 1.5002184514029064}

3it [21:05, 422.44s/it][I 2023-07-06 06:26:31,970] A new study created in memory with name: no-name-7807119f-8a9c-41a3-8855-c0595fabe5f6
[I 2023-07-06 06:27:08,804] Trial 0 finished with value: 0.9178779069767442 and parameters: {'learning_rate': 0.05155075222533945, 'n_estimators': 1021, 'colsample_bytree': 0.719350443033115, 'subsample': 0.8026671775328005, 'reg_alpha': 2.929838278776278, 'reg_lambda': 4.381363801434478}. Best is trial 0 with value: 0.9178779069767442.
[I 2023-07-06 06:27:26,979] Trial 1 finished with value: 0.7740355174525414 and parameters: {'learning_rate': 0.03335122173910602, 'n_estimators': 449, 'colsample_bytree': 0.8939597454392421, 'subsample': 0.90185383175199, 'reg_alpha': 0.8325287193873104, 'reg_lambda': 4.1249853208318505}. Best is trial 0 with value: 0.9178779069767442.
[I 2023-07-06 06:27:44,881] Trial 2 finished with value: 0.8227642276422764 and parameters: {'learning_rate': 0.04819051340299198, 'n_estimators': 426, 'colsample_bytree': 0.8867573880389659, 'subsample': 0.7986835712080858, 'reg_alpha': 1.4341480205048074, 'reg_lambda': 4.11778941543427}. Best is trial 0 with value: 0.9178779069767442.
[I 2023-07-06 06:28:48,574] Trial 3 finished with value: 0.9415270018621974 and parameters: {'learning_rate': 0.049031124189119285, 'n_estimators': 1789, 'colsample_bytree': 0.5354452465687923, 'subsample': 0.6551634914707407, 'reg_alpha': 4.443349592067058, 'reg_lambda': 3.275406024914261}. Best is trial 3 with value: 0.9415270018621974.
[I 2023-07-06 06:29:46,842] Trial 4 finished with value: 0.943410275502606 and parameters: {'learning_rate': 0.06022017902190689, 'n_estimators': 1492, 'colsample_bytree': 0.6792704767870048, 'subsample': 0.5551904219339706, 'reg_alpha': 4.8168769859021126, 'reg_lambda': 2.278705614545406}. Best is trial 4 with value: 0.943410275502606.
[I 2023-07-06 06:30:03,421] Trial 5 finished with value: 0.9054441260744985 and parameters: {'learning_rate': 0.08609403225492421, 'n_estimators': 482, 'colsample_bytree': 0.6371508281671892, 'subsample': 0.7335093601899446, 'reg_alpha': 2.774451765836108, 'reg_lambda': 2.5463458419800755}. Best is trial 4 with value: 0.943410275502606.
[I 2023-07-06 06:30:38,816] Trial 6 finished with value: 0.5474565073772296 and parameters: {'learning_rate': 0.0052700473338712, 'n_estimators': 748, 'colsample_bytree': 0.9391703358009253, 'subsample': 0.9307535035437619, 'reg_alpha': 1.1537401899166926, 'reg_lambda': 2.140944756416896}. Best is trial 4 with value: 0.943410275502606.
[I 2023-07-06 06:30:52,531] Trial 7 finished with value: 0.6438144329896908 and parameters: {'learning_rate': 0.02046710075633703, 'n_estimators': 312, 'colsample_bytree': 0.8025799086836968, 'subsample': 0.5710777399429426, 'reg_alpha': 3.424732965721752, 'reg_lambda': 1.7616310325718232}. Best is trial 4 with value: 0.943410275502606.
[I 2023-07-06 06:31:16,139] Trial 8 finished with value: 0.401481004507405 and parameters: {'learning_rate': 0.002134351994605946, 'n_estimators': 576, 'colsample_bytree': 0.6574551534352904, 'subsample': 0.8514441773938, 'reg_alpha': 0.6611581476272604, 'reg_lambda': 0.3367074235617945}. Best is trial 4 with value: 0.943410275502606.
[I 2023-07-06 06:32:13,076] Trial 9 finished with value: 0.9586964759378552 and parameters: {'learning_rate': 0.08520967733552713, 'n_estimators': 1595, 'colsample_bytree': 0.8305401719936001, 'subsample': 0.7641640601809178, 'reg_alpha': 1.4614539781859777, 'reg_lambda': 1.5002184514029064}. Best is trial 9 with value: 0.9586964759378552.

Best trial : score 0.9586964759378552,
params {'learning_rate': 0.08520967733552713, 'n_estimators': 1595, 'colsample_bytree': 0.8305401719936001, 'subsample': 0.7641640601809178, 'reg_alpha': 1.4614539781859777, 'reg_lambda': 1.5002184514029064}

4it [27:53, 416.81s/it][I 2023-07-06 06:33:20,159] A new study created in memory with name: no-name-5a1aad8d-15bd-4c82-bd40-3e563601171c
[I 2023-07-06 06:34:00,440] Trial 0 finished with value: 0.9053708439897699 and parameters: {'learning_rate': 0.05155075222533945, 'n_estimators': 1021, 'colsample_bytree': 0.719350443033115, 'subsample': 0.8026671775328005, 'reg_alpha': 2.929838278776278, 'reg_lambda': 4.381363801434478}. Best is trial 0 with value: 0.9053708439897699.
[I 2023-07-06 06:34:21,403] Trial 1 finished with value: 0.7689941556444171 and parameters: {'learning_rate': 0.03335122173910602, 'n_estimators': 449, 'colsample_bytree': 0.8939597454392421, 'subsample': 0.90185383175199, 'reg_alpha': 0.8325287193873104, 'reg_lambda': 4.1249853208318505}. Best is trial 0 with value: 0.9053708439897699.
[I 2023-07-06 06:34:38,920] Trial 2 finished with value: 0.8104234527687295 and parameters: {'learning_rate': 0.04819051340299198, 'n_estimators': 426, 'colsample_bytree': 0.8867573880389659, 'subsample': 0.7986835712080858, 'reg_alpha': 1.4341480205048074, 'reg_lambda': 4.11778941543427}. Best is trial 0 with value: 0.9053708439897699.
[I 2023-07-06 06:35:43,770] Trial 3 finished with value: 0.9284116331096196 and parameters: {'learning_rate': 0.049031124189119285, 'n_estimators': 1789, 'colsample_bytree': 0.5354452465687923, 'subsample': 0.6551634914707407, 'reg_alpha': 4.443349592067058, 'reg_lambda': 3.275406024914261}. Best is trial 3 with value: 0.9284116331096196.
[I 2023-07-06 06:36:38,810] Trial 4 finished with value: 0.9327354260089685 and parameters: {'learning_rate': 0.06022017902190689, 'n_estimators': 1492, 'colsample_bytree': 0.6792704767870048, 'subsample': 0.5551904219339706, 'reg_alpha': 4.8168769859021126, 'reg_lambda': 2.278705614545406}. Best is trial 4 with value: 0.9327354260089685.
[I 2023-07-06 06:36:56,462] Trial 5 finished with value: 0.8927931158121191 and parameters: {'learning_rate': 0.08609403225492421, 'n_estimators': 482, 'colsample_bytree': 0.6371508281671892, 'subsample': 0.7335093601899446, 'reg_alpha': 2.774451765836108, 'reg_lambda': 2.5463458419800755}. Best is trial 4 with value: 0.9327354260089685.
[I 2023-07-06 06:37:29,741] Trial 6 finished with value: 0.5409159973952681 and parameters: {'learning_rate': 0.0052700473338712, 'n_estimators': 748, 'colsample_bytree': 0.9391703358009253, 'subsample': 0.9307535035437619, 'reg_alpha': 1.1537401899166926, 'reg_lambda': 2.140944756416896}. Best is trial 4 with value: 0.9327354260089685.
[I 2023-07-06 06:37:48,256] Trial 7 finished with value: 0.6312579415501905 and parameters: {'learning_rate': 0.02046710075633703, 'n_estimators': 312, 'colsample_bytree': 0.8025799086836968, 'subsample': 0.5710777399429426, 'reg_alpha': 3.424732965721752, 'reg_lambda': 1.7616310325718232}. Best is trial 4 with value: 0.9327354260089685.
[I 2023-07-06 06:38:09,754] Trial 8 finished with value: 0.4060814124570868 and parameters: {'learning_rate': 0.002134351994605946, 'n_estimators': 576, 'colsample_bytree': 0.6574551534352904, 'subsample': 0.8514441773938, 'reg_alpha': 0.6611581476272604, 'reg_lambda': 0.3367074235617945}. Best is trial 4 with value: 0.9327354260089685.
[I 2023-07-06 06:39:08,725] Trial 9 finished with value: 0.9578866768759572 and parameters: {'learning_rate': 0.08520967733552713, 'n_estimators': 1595, 'colsample_bytree': 0.8305401719936001, 'subsample': 0.7641640601809178, 'reg_alpha': 1.4614539781859777, 'reg_lambda': 1.5002184514029064}. Best is trial 9 with value: 0.9578866768759572.

Best trial : score 0.9578866768759572,
params {'learning_rate': 0.08520967733552713, 'n_estimators': 1595, 'colsample_bytree': 0.8305401719936001, 'subsample': 0.7641640601809178, 'reg_alpha': 1.4614539781859777, 'reg_lambda': 1.5002184514029064}

5it [34:49, 417.90s/it]

## busan_csv_generation

In [ ]:
data = pd.read_excel('/content/gdrive/MyDrive/2023날씨빅콘/모델/oceanUser.xlsx')
data = data.drop('TARGET',axis =1)

In [ ]:
busan_binary_predict = []
for fold0, fold1, fold2, fold3, fold4 in zip(list(busan_preds[0][0]), list(busan_preds[1][0]), list(busan_preds[2][0]), list(busan_preds[3][0]), list(busan_preds[4][0])):
  if (fold0 >= 0.55) and (fold1 >= 0.55) and (fold2 >= 0.55) and (fold3 >= 0.55) and (fold4 >= 0.55):
    busan_binary_predict.append(1)
  else:
    busan_binary_predict.append(0)

In [ ]:
len(busan_binary_predict)

153299

In [ ]:
busan_data = data.loc[data['AREA']=='BUSAN']

Busan_test = pd.read_csv('/content/gdrive/MyDrive/2023날씨빅콘/final_data/final_csv/가까운거리/부산_가까운거리_test_최종.csv',index_col=0)
Busan_test['target'] = busan_binary_predict
Busan_test = Busan_test.sort_index()
busan_test = Busan_test[['busan_anch_drag_test.time','busan_anch_drag_test.num','target']]

In [ ]:
busan_test

       busan_anch_drag_test.time  busan_anch_drag_test.num  target
0            2022-08-14 00:55:06                      1001       0
1            2022-08-14 00:55:16                      1001       0
2            2022-08-14 00:55:24                      1001       0
3            2022-08-14 00:55:36                      1001       0
4            2022-08-14 00:55:45                      1001       0
...                          ...                       ...     ...
153294       2023-03-08 11:01:43                      1116       0
153295       2023-03-08 11:02:04                      1116       0
153296       2023-03-08 11:02:12                      1116       0
153297       2023-03-08 11:02:22                      1116       0
153298       2023-03-08 11:02:54                      1116       0

[153299 rows x 3 columns]

In [ ]:
busan_test['busan_anch_drag_test.time'] = pd.to_datetime(busan_test['busan_anch_drag_test.time'])
busan_test['YEAR'] = busan_test['busan_anch_drag_test.time'].dt.year
busan_test['MON'] = busan_test['busan_anch_drag_test.time'].dt.month
busan_test['DAY'] = busan_test['busan_anch_drag_test.time'].dt.day
busan_test['HOUR'] = busan_test['busan_anch_drag_test.time'].dt.hour
busan_test['MIN'] = busan_test['busan_anch_drag_test.time'].dt.minute

In [ ]:
busan_test = busan_test.drop('busan_anch_drag_test.time',axis = 1)
busan_test.rename(columns={'busan_anch_drag_test.num':'NUM'},inplace=True)
max_target = busan_test.groupby(['NUM','MON','DAY','HOUR','MIN'])['target'].transform(lambda x:x.max())

In [ ]:
max_target.to_list()
busan_test['target'] = max_target.to_list()

In [ ]:
busan_merge = pd.merge(busan_data,busan_test,on=['NUM','YEAR', 'MON', 'DAY', 'HOUR', 'MIN'] , how='inner')

In [ ]:
busan_merge

         AREA   NUM  YEAR  MON  DAY  HOUR  MIN  target
0       BUSAN  1001  2022    8   14     0   55       0
1       BUSAN  1001  2022    8   14     0   55       0
2       BUSAN  1001  2022    8   14     0   55       0
3       BUSAN  1001  2022    8   14     0   55       0
4       BUSAN  1001  2022    8   14     0   55       0
...       ...   ...   ...  ...  ...   ...  ...     ...
153294  BUSAN  1116  2023    3    8    11    1       0
153295  BUSAN  1116  2023    3    8    11    2       0
153296  BUSAN  1116  2023    3    8    11    2       0
153297  BUSAN  1116  2023    3    8    11    2       0
153298  BUSAN  1116  2023    3    8    11    2       0

[153299 rows x 8 columns]

## ulsan_csv_generation

In [ ]:
ulsan_binary_predict = []
for fold0, fold1, fold2, fold3, fold4 in zip(list(ulsan_preds[0][0]), list(ulsan_preds[1][0]), list(ulsan_preds[2][0]), list(ulsan_preds[3][0]), list(ulsan_preds[4][0])):
  if (fold0 >= 0.) and (fold1 >= 0.7) and (fold2 >= 0.7) and (fold3 >= 0.7) and (fold4 >= 0.7):
    ulsan_binary_predict.append(1)
  else:
    ulsan_binary_predict.append(0)

In [ ]:
Ulsan_test = pd.read_csv('/content/gdrive/MyDrive/2023날씨빅콘/final_data/final_csv/가까운거리/울산_가까운거리_test_최종.csv',index_col=0)

In [ ]:
Ulsan_test['target'] = ulsan_binary_predict

In [ ]:
Ulsan_test = Ulsan_test.sort_index()

In [ ]:
ulsan_test = Ulsan_test[['ulsan_anch_drag_test.time','ulsan_anch_drag_test.num','target']]

In [ ]:
ulsan_test['ulsan_anch_drag_test.time'] = pd.to_datetime(ulsan_test['ulsan_anch_drag_test.time'])
ulsan_test['YEAR'] = ulsan_test['ulsan_anch_drag_test.time'].dt.year
ulsan_test['MON'] = ulsan_test['ulsan_anch_drag_test.time'].dt.month
ulsan_test['DAY'] = ulsan_test['ulsan_anch_drag_test.time'].dt.day
ulsan_test['HOUR'] = ulsan_test['ulsan_anch_drag_test.time'].dt.hour
ulsan_test['MIN'] = ulsan_test['ulsan_anch_drag_test.time'].dt.minute

In [ ]:
ulsan_test = ulsan_test.drop('ulsan_anch_drag_test.time',axis = 1)

In [ ]:
ulsan_test.rename(columns={'ulsan_anch_drag_test.num':'NUM'},inplace=True)

In [ ]:
max_target = ulsan_test.groupby(['NUM','MON','DAY','HOUR','MIN'])['target'].transform(lambda x:x.max())

In [ ]:
ulsan_test['target'] = max_target.to_list()

In [ ]:
ulsan_test

         NUM  target  YEAR  MON  DAY  HOUR  MIN
0       1001       0  2022    8   24    14   41
1       1001       0  2022    8   24    14   41
2       1001       0  2022    8   24    14   41
3       1001       0  2022    8   24    14   42
4       1001       0  2022    8   24    14   42
...      ...     ...   ...  ...  ...   ...  ...
186508  1117       0  2023    1   17    19   44
186509  1117       0  2023    1   17    19   50
186510  1117       0  2023    1   17    19   56
186511  1117       0  2023    1   17    19   59
186512  1117       0  2023    1   17    20    5

[186513 rows x 7 columns]

In [ ]:
ulsan_data = data.loc[data['AREA']=='ULSAN']

In [ ]:
ulsan_merge = pd.merge(ulsan_data,ulsan_test,left_on=['NUM','YEAR', 'MON', 'DAY', 'HOUR', 'MIN'],right_on=['NUM','YEAR', 'MON', 'DAY', 'HOUR', 'MIN'] , how='inner')

In [ ]:
ulsan_merge

         AREA   NUM  YEAR  MON  DAY  HOUR  MIN  target
0       ULSAN  1001  2022    8   24    14   41       0
1       ULSAN  1001  2022    8   24    14   41       0
2       ULSAN  1001  2022    8   24    14   41       0
3       ULSAN  1001  2022    8   24    14   42       0
4       ULSAN  1001  2022    8   24    14   42       0
...       ...   ...   ...  ...  ...   ...  ...     ...
186508  ULSAN  1117  2023    1   17    19   44       0
186509  ULSAN  1117  2023    1   17    19   50       0
186510  ULSAN  1117  2023    1   17    19   56       0
186511  ULSAN  1117  2023    1   17    19   59       0
186512  ULSAN  1117  2023    1   17    20    5       0

[186513 rows x 8 columns]

## ulsan_busan_concat

In [ ]:
df = pd.concat([busan_merge,ulsan_merge],axis=0)

In [ ]:
df.rename(columns={'target':'TARGET'},inplace=True)

In [ ]:
df = df.drop_duplicates()

In [ ]:
len(df)

118815

In [ ]:
df['TARGET'].value_counts()

0    118256
1       559
Name: TARGET, dtype: int64

## prediction_file generation

In [ ]:
import openpyxl
df.to_excel('230066.xlsx',index=False)